package ua.kostenko.tasks.app.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a task entity in the system.
 * <p>
 * This class maps to the "tasks" table in the database and contains information
 * about the task's name, description, and associated user.
 * </p>
 *
 * <p>
 * Each task must have a unique name for a specific user, ensuring that no two
 * tasks for the same user can share the same name.
 * </p>
 */
@Entity
@Table(name = "tasks", schema = "backend_diff", uniqueConstraints = {@UniqueConstraint(columnNames = {"name",
                                                                                                      "user_id"})})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"user"})
@EqualsAndHashCode(exclude = {"user"})
public class Task {

    /**
     * The unique identifier for the task.
     * <p>
     * This value is automatically generated by the database upon task creation.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long taskId;

    /**
     * The name of the task.
     * <p>
     * This field is mandatory and cannot be null.
     * </p>
     */
    @Column(nullable = false)
    private String name;

    /**
     * A brief description of the task.
     * <p>
     * This field is mandatory and cannot be null.
     * </p>
     */
    @Column(nullable = false)
    private String description;

    /**
     * The user associated with the task.
     * <p>
     * This establishes a many-to-one relationship with the User entity.
     * The user_id column in the tasks table serves as a foreign key.
     * This field is mandatory and cannot be null.
     * </p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
}
